export type ModelInfo = {
  id: string;
  name: string;
  provider: string;
  contextWindow?: number;
  maxTokens?: number;
  features?: string[];
  freeTier?: { limit: string; resetPeriod: string };
  pricing?: { input: number; output: number };
};

export const MODEL_REGISTRY: { [provider: string]: ModelInfo[] } = {
  groq: [
    { id: 'llama-3.3-70b-versatile', name: 'Llama 3.3 70B', provider: 'groq', contextWindow: 128000, maxTokens: 32768, features: ['fast', 'versatile', 'reasoning'], freeTier: { limit: '14,400 requests/day', resetPeriod: 'daily' } },
    { id: 'llama-3.1-8b-instant', name: 'Llama 3.1 8B Instant', provider: 'groq', contextWindow: 128000, maxTokens: 8192, features: ['ultra-fast', 'instant'], freeTier: { limit: '30 requests/min', resetPeriod: 'minute' } },
    { id: 'allam-2-7b', name: 'Allam 2 7B', provider: 'groq', contextWindow: 32768, maxTokens: 4096, features: ['arabic', 'fast'], freeTier: { limit: 'Standard', resetPeriod: 'daily' } },
    { id: 'canopylabs/orpheus-arabic-saudi', name: 'Orpheus Arabic Saudi', provider: 'groq', contextWindow: 32768, maxTokens: 4096, features: ['arabic', 'specialized'], freeTier: { limit: 'Standard', resetPeriod: 'daily' } },
    { id: 'canopylabs/orpheus-v1-english', name: 'Orpheus v1 English', provider: 'groq', contextWindow: 32768, maxTokens: 4096, features: ['english', 'specialized'], freeTier: { limit: 'Standard', resetPeriod: 'daily' } },
    { id: 'groq/compound', name: 'Groq Compound', provider: 'groq', contextWindow: 70000, maxTokens: 8192, features: ['compound', 'efficient'], freeTier: { limit: 'Standard', resetPeriod: 'daily' } },
    { id: 'groq/compound-mini', name: 'Groq Compound Mini', provider: 'groq', contextWindow: 70000, maxTokens: 8192, features: ['mini', 'efficient'], freeTier: { limit: 'Standard', resetPeriod: 'daily' } },
    { id: 'meta-llama/llama-4-maverick-17b-128e-instruct', name: 'Llama 4 Maverick 17B', provider: 'groq', contextWindow: 128000, maxTokens: 8192, features: ['experimental', 'new'], freeTier: { limit: 'Limited', resetPeriod: 'daily' } },
    { id: 'meta-llama/llama-4-scout-17b-16e-instruct', name: 'Llama 4 Scout 17B', provider: 'groq', contextWindow: 128000, maxTokens: 8192, features: ['experimental', 'scout'], freeTier: { limit: 'Limited', resetPeriod: 'daily' } },
    { id: 'meta-llama/llama-guard-4-12b', name: 'Llama Guard 4 12B', provider: 'groq', contextWindow: 8192, maxTokens: 4096, features: ['safety', 'guard'], freeTier: { limit: 'Standard', resetPeriod: 'daily' } },
    { id: 'meta-llama/llama-prompt-guard-2-22m', name: 'Llama Prompt Guard 2 22M', provider: 'groq', contextWindow: 8192, maxTokens: 4096, features: ['safety', 'lightweight'], freeTier: { limit: 'Standard', resetPeriod: 'daily' } },
    { id: 'meta-llama/llama-prompt-guard-2-86m', name: 'Llama Prompt Guard 2 86M', provider: 'groq', contextWindow: 8192, maxTokens: 4096, features: ['safety', 'standard'], freeTier: { limit: 'Standard', resetPeriod: 'daily' } },
    { id: 'moonshotai/kimi-k2-instruct', name: 'Kimi k2 Instruct', provider: 'groq', contextWindow: 200000, maxTokens: 8192, features: ['long-context', 'chinese'], freeTier: { limit: 'Standard', resetPeriod: 'daily' } },
    { id: 'moonshotai/kimi-k2-instruct-0905', name: 'Kimi k2 Instruct 0905', provider: 'groq', contextWindow: 200000, maxTokens: 8192, features: ['long-context', 'chinese', 'snapshot'], freeTier: { limit: 'Standard', resetPeriod: 'daily' } },
    { id: 'openai/gpt-oss-120b', name: 'GPT OSS 120B', provider: 'groq', contextWindow: 8192, maxTokens: 4096, features: ['oss', 'large'], freeTier: { limit: 'Standard', resetPeriod: 'daily' } },
    { id: 'openai/gpt-oss-20b', name: 'GPT OSS 20B', provider: 'groq', contextWindow: 8192, maxTokens: 4096, features: ['oss', 'medium'], freeTier: { limit: 'Standard', resetPeriod: 'daily' } },
    { id: 'openai/gpt-oss-safeguard-20b', name: 'GPT OSS Safeguard 20B', provider: 'groq', contextWindow: 8192, maxTokens: 4096, features: ['oss', 'safeguard'], freeTier: { limit: 'Standard', resetPeriod: 'daily' } },
    { id: 'playai-tts', name: 'PlayAI TTS', provider: 'groq', contextWindow: 8192, maxTokens: 1024, features: ['audio', 'tts'], freeTier: { limit: 'Standard', resetPeriod: 'daily' } },
    { id: 'playai-tts-arabic', name: 'PlayAI TTS Arabic', provider: 'groq', contextWindow: 8192, maxTokens: 1024, features: ['audio', 'tts', 'arabic'], freeTier: { limit: 'Standard', resetPeriod: 'daily' } },
    { id: 'qwen/qwen3-32b', name: 'Qwen 3 32B', provider: 'groq', contextWindow: 32768, maxTokens: 8192, features: ['fast', 'multilingual'], freeTier: { limit: 'Standard', resetPeriod: 'daily' } },
    { id: 'whisper-large-v3', name: 'Whisper Large v3', provider: 'groq', contextWindow: 2048, maxTokens: 2048, features: ['audio', 'transcription'], freeTier: { limit: 'Standard', resetPeriod: 'daily' } },
    { id: 'whisper-large-v3-turbo', name: 'Whisper Large v3 Turbo', provider: 'groq', contextWindow: 2048, maxTokens: 2048, features: ['audio', 'transcription', 'fast'], freeTier: { limit: 'Standard', resetPeriod: 'daily' } }
  ],
  google: [
    { id: 'gemini-2.0-flash-exp', name: 'Gemini 2.0 Flash', provider: 'google', contextWindow: 1000000, maxTokens: 8192, features: ['multimodal', 'fast', 'experimental'], freeTier: { limit: '1500 requests/day', resetPeriod: 'daily' } },
    { id: 'gemini-1.5-flash', name: 'Gemini 1.5 Flash', provider: 'google', contextWindow: 1000000, maxTokens: 8192, features: ['multimodal', 'fast'], freeTier: { limit: '1500 requests/day', resetPeriod: 'daily' } }
  ],
  cerebras: [
    { id: 'llama3.1-8b', name: 'Llama 3.1 8B', provider: 'cerebras', contextWindow: 8192, maxTokens: 8192, features: ['ultra-fast', 'efficient'], freeTier: { limit: 'Unlimited (rate limited)', resetPeriod: 'none' } },
    { id: 'llama3.1-70b', name: 'Llama 3.1 70B', provider: 'cerebras', contextWindow: 8192, maxTokens: 8192, features: ['powerful', 'fast'], freeTier: { limit: 'Unlimited (rate limited)', resetPeriod: 'none' } },
    { id: 'qwen-3-32b', name: 'Qwen 3 32B', provider: 'cerebras', contextWindow: 8192, maxTokens: 8192, features: ['fast', 'efficient'], freeTier: { limit: 'Unlimited (rate limited)', resetPeriod: 'none' } },
    { id: 'gpt-oss-120b', name: 'OpenAI GPT OSS 120B', provider: 'cerebras', contextWindow: 8192, maxTokens: 8192, features: ['large', 'powerful'], freeTier: { limit: 'Unlimited (rate limited)', resetPeriod: 'none' } },
    { id: 'zai-glm-4.6', name: 'Z.ai GLM 4.6', provider: 'cerebras', contextWindow: 8192, maxTokens: 8192, features: ['advanced', 'reasoning'], freeTier: { limit: 'Unlimited (rate limited)', resetPeriod: 'none' } },
    { id: 'qwen-3-235b-instruct', name: 'Qwen 3 235B (Instruct)', provider: 'cerebras', contextWindow: 8192, maxTokens: 8192, features: ['mammoth', 'instruct', 'powerful'], freeTier: { limit: 'Unlimited (rate limited)', resetPeriod: 'none' } }
  ],
  sambanova: [
    { id: 'Meta-Llama-3.1-8B-Instruct', name: 'Llama 3.1 8B', provider: 'sambanova', contextWindow: 8192, maxTokens: 8192, features: ['fast', 'efficient'], freeTier: { limit: 'Generous free tier', resetPeriod: 'monthly' } },
    { id: 'Meta-Llama-3.1-70B-Instruct', name: 'Llama 3.1 70B', provider: 'sambanova', contextWindow: 8192, maxTokens: 8192, features: ['powerful', 'accurate'], freeTier: { limit: 'Generous free tier', resetPeriod: 'monthly' } }
  ],
  openai: [
    { id: 'gpt-4o-mini', name: 'GPT-4o Mini', provider: 'openai', contextWindow: 128000, maxTokens: 16384, features: ['fast', 'affordable', 'multimodal'], pricing: { input: 0.00015, output: 0.0006 } },
    { id: 'gpt-4o', name: 'GPT-4o', provider: 'openai', contextWindow: 128000, maxTokens: 16384, features: ['powerful', 'multimodal', 'latest'], pricing: { input: 0.0025, output: 0.01 } }
  ],
  anthropic: [
    { id: 'claude-3-5-sonnet-20241022', name: 'Claude 3.5 Sonnet', provider: 'anthropic', contextWindow: 200000, maxTokens: 8192, features: ['powerful', 'reasoning', 'coding'], pricing: { input: 0.003, output: 0.015 } },
    { id: 'claude-3-5-haiku-20241022', name: 'Claude 3.5 Haiku', provider: 'anthropic', contextWindow: 200000, maxTokens: 8192, features: ['fast', 'affordable'], pricing: { input: 0.0008, output: 0.004 } }
  ],
  xai: [
    { id: 'grok-4-latest', name: 'Grok 4 (Latest)', provider: 'xai', contextWindow: 128000, maxTokens: 4096, features: ['intelligence', 'latest'], pricing: { input: 0, output: 0 } },
    { id: 'grok-beta', name: 'Grok Beta', provider: 'xai', contextWindow: 128000, maxTokens: 4096, features: ['beta', 'reasoning'], pricing: { input: 0, output: 0 } },
    { id: 'grok-3', name: 'Grok 3', provider: 'xai', contextWindow: 128000, maxTokens: 4096, features: ['fast', 'stable'], pricing: { input: 0, output: 0 } },
    { id: 'grok-2', name: 'Grok 2', provider: 'xai', contextWindow: 128000, maxTokens: 4096, features: ['standard', 'efficient'], pricing: { input: 0, output: 0 } }
  ],
  novita: [
    { id: 'kat-coder', name: 'Kat Coder', provider: 'novita', contextWindow: 32000, maxTokens: 1000, features: ['coding', 'efficient'], pricing: { input: 0, output: 0 } }
  ],
  bytez: [
    { id: 'google/gemma-3-4b-it', name: 'Gemma 3 4B', provider: 'bytez', contextWindow: 8192, maxTokens: 4096, features: ['google', 'chat'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'sentence-transformers/all-MiniLM-L6-v2', name: 'All MiniLM L6 v2', provider: 'bytez', contextWindow: 512, maxTokens: 512, features: ['embedding', 'fast'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'stabilityai/stable-diffusion-xl-base-1.0', name: 'Stable Diffusion XL 1.0', provider: 'bytez', contextWindow: 77, maxTokens: 1024, features: ['image', 'generation'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Qwen/Qwen3-0.6B', name: 'Qwen 3 0.6B', provider: 'bytez', contextWindow: 32768, maxTokens: 4096, features: ['qwen', 'chat', 'lightweight'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'openai/whisper-large-v3', name: 'Whisper Large v3', provider: 'bytez', contextWindow: 8192, maxTokens: 4096, features: ['audio', 'transcription'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'google/gemma-3-1b-it', name: 'Gemma 3 1B', provider: 'bytez', contextWindow: 8192, maxTokens: 4096, features: ['google', 'chat', 'lightweight'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'openai-community/gpt2', name: 'GPT-2', provider: 'bytez', contextWindow: 1024, maxTokens: 1024, features: ['classic', 'chat'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'TinyLlama/TinyLlama-1.1B-Chat-v1.0', name: 'TinyLlama 1.1B', provider: 'bytez', contextWindow: 2048, maxTokens: 2048, features: ['tiny', 'chat'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'openai/clip-vit-large-patch14', name: 'CLIP ViT Large', provider: 'bytez', contextWindow: 77, maxTokens: 512, features: ['vision', 'embedding'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'BAAI/bge-m3', name: 'BGE M3', provider: 'bytez', contextWindow: 8192, maxTokens: 512, features: ['embedding', 'multilingual'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'stable-diffusion-v1-5/stable-diffusion-v1-5', name: 'Stable Diffusion v1.5', provider: 'bytez', contextWindow: 77, maxTokens: 1024, features: ['image', 'generation'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'openai/whisper-large-v3-turbo', name: 'Whisper Large v3 Turbo', provider: 'bytez', contextWindow: 8192, maxTokens: 4096, features: ['audio', 'transcription', 'fast'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Qwen/Qwen3-1.7B', name: 'Qwen 3 1.7B', provider: 'bytez', contextWindow: 32768, maxTokens: 4096, features: ['qwen', 'chat'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Qwen/Qwen3-4B-Thinking-2507', name: 'Qwen 3 4B Thinking', provider: 'bytez', contextWindow: 32768, maxTokens: 4096, features: ['qwen', 'chat', 'reasoning'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Qwen/Qwen3-4B-Instruct-2507', name: 'Qwen 3 4B Instruct', provider: 'bytez', contextWindow: 32768, maxTokens: 4096, features: ['qwen', 'chat', 'instruct'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'ibm-granite/granite-docling-258M', name: 'Granite Docling', provider: 'bytez', contextWindow: 8192, maxTokens: 4096, features: ['document', 'processing'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'microsoft/Phi-3-mini-4k-instruct', name: 'Phi-3 Mini 4k', provider: 'bytez', contextWindow: 4096, maxTokens: 4096, features: ['microsoft', 'chat', 'small'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'facebook/bart-large-mnli', name: 'BART Large MNLI', provider: 'bytez', contextWindow: 1024, maxTokens: 1024, features: ['classification', 'nli'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'suno/bark', name: 'Suno Bark', provider: 'bytez', contextWindow: 1024, maxTokens: 1024, features: ['audio', 'generation'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'google/siglip-so400m-patch14-384', name: 'SigLIP SO400M', provider: 'bytez', contextWindow: 77, maxTokens: 512, features: ['vision', 'embedding'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2', name: 'Paraphrase Multi L12', provider: 'bytez', contextWindow: 512, maxTokens: 512, features: ['embedding', 'multilingual'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'sentence-transformers/paraphrase-multilingual-mpnet-base-v2', name: 'Paraphrase Multi MPNet', provider: 'bytez', contextWindow: 512, maxTokens: 512, features: ['embedding', 'multilingual'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'nomic-ai/nomic-embed-text-v1.5', name: 'Nomic Embed 1.5', provider: 'bytez', contextWindow: 8192, maxTokens: 8192, features: ['embedding'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'google/madlad400-3b-mt', name: 'MADLAD-400 3B MT', provider: 'bytez', contextWindow: 2048, maxTokens: 2048, features: ['translation'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'facebook/bart-large-cnn', name: 'BART Large CNN', provider: 'bytez', contextWindow: 1024, maxTokens: 1024, features: ['summarization'], freeTier: { limit: 'Standard', resetPeriod: 'none' } }
  ],
  aimlapi: [
    { id: 'qwen-max', name: 'Qwen Max', provider: 'aimlapi', contextWindow: 32768, maxTokens: 8192, features: ['advanced', 'reasoning'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'qwen-plus', name: 'Qwen Plus', provider: 'aimlapi', contextWindow: 32768, maxTokens: 8192, features: ['balanced', 'fast'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'qwen-turbo', name: 'Qwen Turbo', provider: 'aimlapi', contextWindow: 32768, maxTokens: 8192, features: ['fast', 'efficient'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Qwen2.5-7B-Instruct-Turbo', name: 'Qwen 2.5 7B Turbo', provider: 'aimlapi', contextWindow: 32768, maxTokens: 8192, features: ['fast', 'instruct'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Qwen2.5-72B-Instruct-Turbo', name: 'Qwen 2.5 72B Turbo', provider: 'aimlapi', contextWindow: 32768, maxTokens: 8192, features: ['powerful', 'instruct'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Qwen2.5-Coder-32B-Instruct', name: 'Qwen 2.5 Coder 32B', provider: 'aimlapi', contextWindow: 32768, maxTokens: 8192, features: ['coding', 'instruct'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Qwen3-235B-A22B', name: 'Qwen 3 235B', provider: 'aimlapi', contextWindow: 32768, maxTokens: 8192, features: ['mammoth', 'powerful'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'qwen3-32b', name: 'Qwen 3 32B', provider: 'aimlapi', contextWindow: 32768, maxTokens: 8192, features: ['balanced', 'latest'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'qwen3-coder-480b-a35b-instruct', name: 'Qwen 3 Coder 480B', provider: 'aimlapi', contextWindow: 32768, maxTokens: 8192, features: ['coding', 'massive'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'qwen3-235b-a22b-thinking-2507', name: 'Qwen 3 235B Thinking', provider: 'aimlapi', contextWindow: 32768, maxTokens: 8192, features: ['reasoning', 'thinking'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'qwen3-next-80b-a3b-instruct', name: 'Qwen 3 Next 80B', provider: 'aimlapi', contextWindow: 32768, maxTokens: 8192, features: ['next-gen', 'instruct'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'qwen3-next-80b-a3b-thinking', name: 'Qwen 3 Next 80B Thinking', provider: 'aimlapi', contextWindow: 32768, maxTokens: 8192, features: ['next-gen', 'thinking'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'qwen3-max-preview', name: 'Qwen 3 Max Preview', provider: 'aimlapi', contextWindow: 32768, maxTokens: 8192, features: ['preview', 'advanced'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'qwen3-max-instruct', name: 'Qwen 3 Max Instruct', provider: 'aimlapi', contextWindow: 32768, maxTokens: 8192, features: ['instruct', 'max'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'qwen3-omni-30b-a3b-captioner', name: 'Qwen 3 Omni 30B', provider: 'aimlapi', contextWindow: 32768, maxTokens: 8192, features: ['multimodal', 'captioner'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'qwen3-vl-32b-instruct', name: 'Qwen 3 VL 32B', provider: 'aimlapi', contextWindow: 32768, maxTokens: 8192, features: ['vision', 'instruct'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'qwen3-vl-32b-thinking', name: 'Qwen 3 VL 32B Thinking', provider: 'aimlapi', contextWindow: 32768, maxTokens: 8192, features: ['vision', 'thinking'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'glm-4.5-air', name: 'GLM 4.5 Air', provider: 'aimlapi', contextWindow: 32768, maxTokens: 8192, features: ['fast'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'glm-4.5', name: 'GLM 4.5', provider: 'aimlapi', contextWindow: 32768, maxTokens: 8192, features: ['standard'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'glm-4.6', name: 'GLM 4.6', provider: 'aimlapi', contextWindow: 32768, maxTokens: 8192, features: ['advanced'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'glm-4.7', name: 'GLM 4.7', provider: 'aimlapi', contextWindow: 32768, maxTokens: 8192, features: ['latest'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'grok-3-beta', name: 'Grok 3 Beta', provider: 'aimlapi', contextWindow: 128000, maxTokens: 8192, features: ['beta'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'grok-3-mini-beta', name: 'Grok 3 Mini Beta', provider: 'aimlapi', contextWindow: 128000, maxTokens: 8192, features: ['mini', 'beta'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'grok-4', name: 'Grok 4', provider: 'aimlapi', contextWindow: 128000, maxTokens: 8192, features: ['latest'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'grok-code-fast-1', name: 'Grok Code Fast 1', provider: 'aimlapi', contextWindow: 128000, maxTokens: 8192, features: ['coding', 'fast'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'grok-4-fast-non-reasoning', name: 'Grok 4 Fast (Non-Reasoning)', provider: 'aimlapi', contextWindow: 128000, maxTokens: 8192, features: ['fast'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'grok-4-fast-reasoning', name: 'Grok 4 Fast (Reasoning)', provider: 'aimlapi', contextWindow: 128000, maxTokens: 8192, features: ['fast', 'reasoning'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'grok-4.1-fast-non-reasoning', name: 'Grok 4.1 Fast (Non-Reasoning)', provider: 'aimlapi', contextWindow: 128000, maxTokens: 8192, features: ['fast', 'latest'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'grok-4.1-fast-reasoning', name: 'Grok 4.1 Fast (Reasoning)', provider: 'aimlapi', contextWindow: 128000, maxTokens: 8192, features: ['fast', 'reasoning'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'sonar', name: 'Sonar', provider: 'aimlapi', contextWindow: 32768, maxTokens: 4096, features: ['search'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'sonar-pro', name: 'Sonar Pro', provider: 'aimlapi', contextWindow: 32768, maxTokens: 4096, features: ['search', 'pro'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-3.5-turbo', name: 'GPT-3.5 Turbo', provider: 'aimlapi', contextWindow: 16384, maxTokens: 4096, features: ['classic'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-4', name: 'GPT-4', provider: 'aimlapi', contextWindow: 8192, maxTokens: 8192, features: ['powerful'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-4-preview', name: 'GPT-4 Preview', provider: 'aimlapi', contextWindow: 128000, maxTokens: 8192, features: ['preview'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-4-turbo', name: 'GPT-4 Turbo', provider: 'aimlapi', contextWindow: 128000, maxTokens: 4096, features: ['turbo'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-4o', name: 'GPT-4o', provider: 'aimlapi', contextWindow: 128000, maxTokens: 4096, features: ['omni'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-4o-mini', name: 'GPT-4o Mini', provider: 'aimlapi', contextWindow: 128000, maxTokens: 16384, features: ['omni', 'mini'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-4o-audio-preview', name: 'GPT-4o Audio Preview', provider: 'aimlapi', contextWindow: 128000, maxTokens: 16384, features: ['audio', 'preview'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-4o-mini-audio-preview', name: 'GPT-4o Mini Audio Preview', provider: 'aimlapi', contextWindow: 128000, maxTokens: 16384, features: ['audio', 'preview'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-4o-search-preview', name: 'GPT-4o Search Preview', provider: 'aimlapi', contextWindow: 128000, maxTokens: 16384, features: ['search', 'preview'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-4o-mini-search-preview', name: 'GPT-4o Mini Search Preview', provider: 'aimlapi', contextWindow: 128000, maxTokens: 16384, features: ['search', 'preview'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'o1', name: 'OpenAI o1', provider: 'aimlapi', contextWindow: 128000, maxTokens: 32768, features: ['reasoning'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'o3', name: 'OpenAI o3', provider: 'aimlapi', contextWindow: 128000, maxTokens: 32768, features: ['reasoning', 'new'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'o3-mini', name: 'OpenAI o3 Mini', provider: 'aimlapi', contextWindow: 128000, maxTokens: 32768, features: ['reasoning', 'mini'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'o3-pro', name: 'OpenAI o3 Pro', provider: 'aimlapi', contextWindow: 128000, maxTokens: 32768, features: ['reasoning', 'pro'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-4.1', name: 'GPT-4.1', provider: 'aimlapi', contextWindow: 128000, maxTokens: 16384, features: ['experimental'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-4.1-mini', name: 'GPT-4.1 Mini', provider: 'aimlapi', contextWindow: 128000, maxTokens: 16384, features: ['experimental', 'mini'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-4.1-nano', name: 'GPT-4.1 Nano', provider: 'aimlapi', contextWindow: 32768, maxTokens: 4096, features: ['experimental', 'nano'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'o4-mini', name: 'OpenAI o4 Mini', provider: 'aimlapi', contextWindow: 128000, maxTokens: 32768, features: ['future', 'mini'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-oss-20b', name: 'GPT OSS 20B', provider: 'aimlapi', contextWindow: 8192, maxTokens: 4096, features: ['oss'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-oss-120b', name: 'GPT OSS 120B', provider: 'aimlapi', contextWindow: 8192, maxTokens: 4096, features: ['oss'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-5', name: 'GPT-5', provider: 'aimlapi', contextWindow: 200000, maxTokens: 32768, features: ['future'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-5-mini', name: 'GPT-5 Mini', provider: 'aimlapi', contextWindow: 200000, maxTokens: 32768, features: ['future', 'mini'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-5-nano', name: 'GPT-5 Nano', provider: 'aimlapi', contextWindow: 128000, maxTokens: 16384, features: ['future', 'nano'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-5-chat', name: 'GPT-5 Chat', provider: 'aimlapi', contextWindow: 200000, maxTokens: 32768, features: ['future'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-5-pro', name: 'GPT-5 Pro', provider: 'aimlapi', contextWindow: 200000, maxTokens: 64000, features: ['future', 'pro'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-5.1', name: 'GPT-5.1', provider: 'aimlapi', contextWindow: 200000, maxTokens: 32768, features: ['future', 'advanced'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-5.1-chat-latest', name: 'GPT-5.1 Chat Latest', provider: 'aimlapi', contextWindow: 200000, maxTokens: 32768, features: ['future'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-5.1-codex', name: 'GPT-5.1 Codex', provider: 'aimlapi', contextWindow: 128000, maxTokens: 32768, features: ['coding', 'future'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-5.1-codex-mini', name: 'GPT-5.1 Codex Mini', provider: 'aimlapi', contextWindow: 128000, maxTokens: 32768, features: ['coding', 'mini'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-5.2', name: 'GPT-5.2', provider: 'aimlapi', contextWindow: 200000, maxTokens: 32768, features: ['future', 'advanced'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-5.2-chat-latest', name: 'GPT-5.2 Chat Latest', provider: 'aimlapi', contextWindow: 200000, maxTokens: 32768, features: ['future'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-5.2-pro', name: 'GPT-5.2 Pro', provider: 'aimlapi', contextWindow: 200000, maxTokens: 64000, features: ['future', 'pro'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'llama-3.1-nemotron-70b', name: 'Llama 3.1 Nemotron 70B', provider: 'aimlapi', contextWindow: 32768, maxTokens: 4096, features: ['nvidia', 'custom'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'nemotron-nano-9b-v2', name: 'Nemotron Nano 9B v2', provider: 'aimlapi', contextWindow: 8192, maxTokens: 4096, features: ['nvidia', 'nano'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'nemotron-nano-12b-v2-vl', name: 'Nemotron Nano 12B VL', provider: 'aimlapi', contextWindow: 8192, maxTokens: 4096, features: ['nvidia', 'vision'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'kimi-k2-preview', name: 'Kimi K2 Preview', provider: 'aimlapi', contextWindow: 200000, maxTokens: 8192, features: ['chinese', 'long-context'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'kimi-k2-turbo-preview', name: 'Kimi K2 Turbo Preview', provider: 'aimlapi', contextWindow: 200000, maxTokens: 8192, features: ['chinese', 'turbo'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Llama-3-chat-hf', name: 'Llama 3 Chat HF', provider: 'aimlapi', contextWindow: 8192, maxTokens: 4096, features: ['meta'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Llama-3-8B-Instruct-Lite', name: 'Llama 3 8B Lite', provider: 'aimlapi', contextWindow: 8192, maxTokens: 4096, features: ['meta', 'lite'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Llama-3.1-8B-Instruct-Turbo', name: 'Llama 3.1 8B Turbo', provider: 'aimlapi', contextWindow: 128000, maxTokens: 8192, features: ['meta', 'turbo'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Llama-3.1-70B-Instruct-Turbo', name: 'Llama 3.1 70B Turbo', provider: 'aimlapi', contextWindow: 128000, maxTokens: 8192, features: ['meta', 'turbo'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Llama-3.1-405B-Instruct-Turbo', name: 'Llama 3.1 405B Turbo', provider: 'aimlapi', contextWindow: 128000, maxTokens: 8192, features: ['meta', 'turbo', 'massive'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Llama-3.2-3B-Instruct-Turbo', name: 'Llama 3.2 3B Turbo', provider: 'aimlapi', contextWindow: 128000, maxTokens: 8192, features: ['meta', 'small', 'turbo'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Llama-3.3-70B-Instruct-Turbo', name: 'Llama 3.3 70B Turbo', provider: 'aimlapi', contextWindow: 128000, maxTokens: 8192, features: ['meta', 'new', 'turbo'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Llama-3.3-70B-Versatile', name: 'Llama 3.3 70B Versatile', provider: 'aimlapi', contextWindow: 128000, maxTokens: 8192, features: ['meta', 'new'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Llama-4-scout', name: 'Llama 4 Scout', provider: 'aimlapi', contextWindow: 128000, maxTokens: 8192, features: ['meta', 'experimental'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Llama-4-maverick', name: 'Llama 4 Maverick', provider: 'aimlapi', contextWindow: 128000, maxTokens: 8192, features: ['meta', 'experimental'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gemini-2.0-flash-exp', name: 'Gemini 2.0 Flash Exp', provider: 'aimlapi', contextWindow: 1000000, maxTokens: 8192, features: ['google', 'flash'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gemini-2.0-flash', name: 'Gemini 2.0 Flash', provider: 'aimlapi', contextWindow: 1000000, maxTokens: 8192, features: ['google', 'flash'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gemini-2.5-flash-lite-preview', name: 'Gemini 2.5 Flash Lite', provider: 'aimlapi', contextWindow: 1000000, maxTokens: 8192, features: ['google', 'lite'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gemini-2.5-flash', name: 'Gemini 2.5 Flash', provider: 'aimlapi', contextWindow: 1000000, maxTokens: 8192, features: ['google', 'flash', 'new'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gemini-2.5-pro', name: 'Gemini 2.5 Pro', provider: 'aimlapi', contextWindow: 2000000, maxTokens: 8192, features: ['google', 'pro', 'new'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gemini-3-pro-preview', name: 'Gemini 3 Pro Preview', provider: 'aimlapi', contextWindow: 2000000, maxTokens: 8192, features: ['google', 'future'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gemma-3', name: 'Gemma 3', provider: 'aimlapi', contextWindow: 8192, maxTokens: 4096, features: ['google', 'open'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gemma-3n-4b', name: 'Gemma 3n 4B', provider: 'aimlapi', contextWindow: 8192, maxTokens: 4096, features: ['google', 'small'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gemini-3-flash-preview', name: 'Gemini 3 Flash Preview', provider: 'aimlapi', contextWindow: 1000000, maxTokens: 8192, features: ['google', 'future'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'DeepSeek V3', name: 'DeepSeek V3', provider: 'aimlapi', contextWindow: 32768, maxTokens: 4096, features: ['deepseek'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'DeepSeek R1', name: 'DeepSeek R1', provider: 'aimlapi', contextWindow: 32768, maxTokens: 4096, features: ['deepseek', 'reasoning'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'DeepSeek Prover V2', name: 'DeepSeek Prover V2', provider: 'aimlapi', contextWindow: 32768, maxTokens: 4096, features: ['deepseek', 'math'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'DeepSeek Chat V3.1', name: 'DeepSeek Chat V3.1', provider: 'aimlapi', contextWindow: 32768, maxTokens: 4096, features: ['deepseek', 'chat'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'DeepSeek Reasoner V3.1', name: 'DeepSeek Reasoner V3.1', provider: 'aimlapi', contextWindow: 32768, maxTokens: 4096, features: ['deepseek', 'reasoning'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Deepseek Non-reasoner V3.1 Terminus', name: 'DeepSeek V3.1 Terminus', provider: 'aimlapi', contextWindow: 32768, maxTokens: 4096, features: ['deepseek'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Deepseek Reasoner V3.1 Terminus', name: 'DeepSeek Reasoner V3.1 T', provider: 'aimlapi', contextWindow: 32768, maxTokens: 4096, features: ['deepseek', 'reasoning'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'DeepSeek V3.2 Exp Non-thinking', name: 'DeepSeek V3.2 Exp', provider: 'aimlapi', contextWindow: 32768, maxTokens: 4096, features: ['deepseek', 'experimental'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'DeepSeek V3.2 Exp Thinking', name: 'DeepSeek V3.2 Exp Think', provider: 'aimlapi', contextWindow: 32768, maxTokens: 4096, features: ['deepseek', 'experimental', 'reasoning'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Claude 3 Haiku', name: 'Claude 3 Haiku', provider: 'aimlapi', contextWindow: 200000, maxTokens: 4096, features: ['anthropic', 'fast'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Claude 3 Opus', name: 'Claude 3 Opus', provider: 'aimlapi', contextWindow: 200000, maxTokens: 4096, features: ['anthropic', 'powerful'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Claude 3.5 Haiku', name: 'Claude 3.5 Haiku', provider: 'aimlapi', contextWindow: 200000, maxTokens: 8192, features: ['anthropic', 'fast', 'new'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Claude 3.7 Sonnet', name: 'Claude 3.7 Sonnet', provider: 'aimlapi', contextWindow: 200000, maxTokens: 8192, features: ['anthropic', 'balanced'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Claude 4 Opus', name: 'Claude 4 Opus', provider: 'aimlapi', contextWindow: 200000, maxTokens: 4096, features: ['anthropic', 'powerful'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Claude 4 Sonnet', name: 'Claude 4 Sonnet', provider: 'aimlapi', contextWindow: 200000, maxTokens: 8192, features: ['anthropic', 'balanced'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Claude 4.1 Opus', name: 'Claude 4.1 Opus', provider: 'aimlapi', contextWindow: 200000, maxTokens: 8192, features: ['anthropic', 'new'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Claude 4.5 Sonnet', name: 'Claude 4.5 Sonnet', provider: 'aimlapi', contextWindow: 200000, maxTokens: 8192, features: ['anthropic', 'new'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Claude 4.5 Haiku', name: 'Claude 4.5 Haiku', provider: 'aimlapi', contextWindow: 200000, maxTokens: 8192, features: ['anthropic', 'fast', 'new'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Claude 4.5 Opus', name: 'Claude 4.5 Opus', provider: 'aimlapi', contextWindow: 200000, maxTokens: 8192, features: ['anthropic', 'powerful', 'new'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'qwen-image', name: 'Qwen Image', provider: 'aimlapi', contextWindow: 0, maxTokens: 0, features: ['image'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'qwen-image-edit', name: 'Qwen Image Edit', provider: 'aimlapi', contextWindow: 0, maxTokens: 0, features: ['image', 'edit'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'z-image-turbo', name: 'Z Image Turbo', provider: 'aimlapi', contextWindow: 0, maxTokens: 0, features: ['image', 'fast'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'z-image-turbo-lora', name: 'Z Image Turbo LoRA', provider: 'aimlapi', contextWindow: 0, maxTokens: 0, features: ['image', 'lora'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Imagen 4 Fast Generate', name: 'Imagen 4 Fast', provider: 'aimlapi', contextWindow: 0, maxTokens: 0, features: ['google', 'image'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Imagen 4 Ultra Generate', name: 'Imagen 4 Ultra', provider: 'aimlapi', contextWindow: 0, maxTokens: 0, features: ['google', 'image'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Gemini 2.5 Flash Image (Nano Banana)', name: 'Gemini 2.5 Flash Image', provider: 'aimlapi', contextWindow: 0, maxTokens: 0, features: ['google', 'image'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Gemini 2.5 Flash Image Edit (Nano Banana)', name: 'Gemini 2.5 Image Edit', provider: 'aimlapi', contextWindow: 0, maxTokens: 0, features: ['google', 'edit'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Nano Banana Pro (Gemini 3 Pro Image)', name: 'Gemini 3 Pro Image', provider: 'aimlapi', contextWindow: 0, maxTokens: 0, features: ['google', 'image', 'pro'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Nano Banana Pro Edit (Gemini 3 Pro Image Edit)', name: 'Gemini 3 Pro Edit', provider: 'aimlapi', contextWindow: 0, maxTokens: 0, features: ['google', 'edit', 'pro'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'grok-2-image', name: 'Grok 2 Image', provider: 'aimlapi', contextWindow: 0, maxTokens: 0, features: ['xai', 'image'], freeTier: { limit: 'Standard', resetPeriod: 'none' } }
  ],

  mistral: [
    { id: 'mistral-large-latest', name: 'Mistral Large', provider: 'mistral', contextWindow: 131000, maxTokens: 32768, features: ['powerful', 'flagship'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'pixtral-large-latest', name: 'Pixtral Large', provider: 'mistral', contextWindow: 131000, maxTokens: 32768, features: ['vision', 'powerful'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'ministral-8b-latest', name: 'Ministral 8B', provider: 'mistral', contextWindow: 131000, maxTokens: 32768, features: ['fast', 'efficient'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'codestral-latest', name: 'Codestral', provider: 'mistral', contextWindow: 32768, maxTokens: 32768, features: ['coding'], freeTier: { limit: 'Standard', resetPeriod: 'none' } }
  ],
  together: [
    { id: 'meta-llama/Llama-3.3-70B-Instruct-Turbo', name: 'Llama 3.3 70B Turbo', provider: 'together', contextWindow: 131000, maxTokens: 4096, features: ['fast', 'turbo'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'deepseek-ai/DeepSeek-V3', name: 'DeepSeek V3', provider: 'together', contextWindow: 131000, maxTokens: 4096, features: ['advanced'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'deepseek-ai/DeepSeek-R1', name: 'DeepSeek R1', provider: 'together', contextWindow: 131000, maxTokens: 4096, features: ['reasoning'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'Qwen/Qwen2.5-72B-Instruct-Turbo', name: 'Qwen 2.5 72B Turbo', provider: 'together', contextWindow: 32768, maxTokens: 4096, features: ['fast', 'instruct'], freeTier: { limit: 'Standard', resetPeriod: 'none' } }
  ],
  deepseek: [
    { id: 'deepseek-chat', name: 'DeepSeek V3 Chat', provider: 'deepseek', contextWindow: 65536, maxTokens: 8192, features: ['chat', 'advanced'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'deepseek-reasoner', name: 'DeepSeek R1 Reasoner', provider: 'deepseek', contextWindow: 65536, maxTokens: 8192, features: ['reasoning'], freeTier: { limit: 'Standard', resetPeriod: 'none' } }
  ],
  fireworks: [
    { id: 'accounts/fireworks/models/llama-v3p3-70b-instruct', name: 'Llama 3.3 70B', provider: 'fireworks', contextWindow: 131000, maxTokens: 4096, features: ['fast', 'instruct'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'accounts/fireworks/models/qwen2p5-72b-instruct', name: 'Qwen 2.5 72B', provider: 'fireworks', contextWindow: 32768, maxTokens: 4096, features: ['fast', 'instruct'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'accounts/fireworks/models/deepseek-v3', name: 'DeepSeek V3', provider: 'fireworks', contextWindow: 131000, maxTokens: 4096, features: ['advanced'], freeTier: { limit: 'Standard', resetPeriod: 'none' } }
  ],
  perplexity: [
    { id: 'sonar-reasoning-pro', name: 'Sonar Reasoning Pro', provider: 'perplexity', contextWindow: 127000, maxTokens: 8192, features: ['search', 'reasoning', 'pro'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'sonar-reasoning', name: 'Sonar Reasoning', provider: 'perplexity', contextWindow: 127000, maxTokens: 4096, features: ['search', 'reasoning'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'sonar-pro', name: 'Sonar Pro', provider: 'perplexity', contextWindow: 200000, maxTokens: 8192, features: ['search', 'pro'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'sonar', name: 'Sonar', provider: 'perplexity', contextWindow: 127000, maxTokens: 4096, features: ['search'], freeTier: { limit: 'Standard', resetPeriod: 'none' } }
  ],
  tokenharbor: [
    { id: 'claude-opus-5', name: 'Claude Opus 5', provider: 'tokenharbor', contextWindow: 200000, maxTokens: 8192, features: ['frontier'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gpt-5.6-sol', name: 'GPT-5.6 Sol', provider: 'tokenharbor', contextWindow: 128000, maxTokens: 8192, features: ['frontier'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'kimi-k3', name: 'Kimi K3', provider: 'tokenharbor', contextWindow: 128000, maxTokens: 8192, features: ['frontier'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'qwen3.8-max', name: 'Qwen3.8 Max', provider: 'tokenharbor', contextWindow: 32768, maxTokens: 8192, features: ['frontier'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'grok-4.5', name: 'Grok 4.5', provider: 'tokenharbor', contextWindow: 128000, maxTokens: 8192, features: ['frontier'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'gemini-3.6-flash', name: 'Gemini 3.6 Flash', provider: 'tokenharbor', contextWindow: 1000000, maxTokens: 8192, features: ['frontier'], freeTier: { limit: 'Standard', resetPeriod: 'none' } },
    { id: 'deepseek-v4-flash', name: 'DeepSeek V4 Flash', provider: 'tokenharbor', contextWindow: 131000, maxTokens: 8192, features: ['value'], freeTier: { limit: 'Standard', resetPeriod: 'none' } }
  ],
  aiand: [
    { id: 'qwen/qwen3.6-27b', name: 'Qwen 3.6 27B', provider: 'aiand', contextWindow: 262000, maxTokens: 8192, features: ['reasoning', 'tool_calling'], freeTier: { limit: 'Free', resetPeriod: 'none' } },
    { id: 'deepseek-ai/deepseek-v4-flash', name: 'DeepSeek V4 Flash', provider: 'aiand', contextWindow: 1000000, maxTokens: 8192, features: ['reasoning', 'tool_calling'], pricing: { input: 0.15, output: 0.25 } },
    { id: 'google/gemma-4-31b-it', name: 'Gemma 4 31B IT', provider: 'aiand', contextWindow: 262000, maxTokens: 8192, features: ['reasoning', 'tool_calling', 'vision', 'video', 'document'], pricing: { input: 0.20, output: 0.50 } },
    { id: 'openai/gpt-oss-120b', name: 'GPT OSS 120B', provider: 'aiand', contextWindow: 131000, maxTokens: 8192, features: ['reasoning', 'tool_calling'], pricing: { input: 0.15, output: 0.60 } },
    { id: 'deepseek-ai/deepseek-v4-pro', name: 'DeepSeek V4 Pro', provider: 'aiand', contextWindow: 1000000, maxTokens: 8192, features: ['reasoning', 'tool_calling'], pricing: { input: 1.00, output: 2.50 } },
    { id: 'moonshotai/kimi-k2.7-code', name: 'Kimi K2.7 Code', provider: 'aiand', contextWindow: 262000, maxTokens: 8192, features: ['reasoning', 'tool_calling', 'vision', 'document'], pricing: { input: 0.75, output: 3.50 } },
    { id: 'moonshotai/kimi-k2.6', name: 'Kimi K2.6', provider: 'aiand', contextWindow: 262000, maxTokens: 8192, features: ['reasoning', 'tool_calling', 'vision', 'document'], pricing: { input: 0.85, output: 3.50 } },
    { id: 'zai-org/glm-5.2', name: 'GLM 5.2', provider: 'aiand', contextWindow: 1000000, maxTokens: 8192, features: ['reasoning', 'tool_calling'], pricing: { input: 1.00, output: 4.00 } },
    { id: 'zai-org/glm-5.1', name: 'GLM 5.1', provider: 'aiand', contextWindow: 203000, maxTokens: 8192, features: ['reasoning', 'tool_calling'], pricing: { input: 1.40, output: 4.40 } }
  ]

};